/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappGroupWebhookParticipant Participant information included in group webhook payloads.
type WhatsappGroupWebhookParticipant struct {
	// The original participant input.
	Input *string `json:"input,omitempty"`
	// WhatsApp user ID.
	WaId *string `json:"waId,omitempty"`
	// Business-scoped user ID.
	RecipientUserId *string `json:"recipientUserId,omitempty"`
	// Parent business-scoped user ID.
	ParentRecipientUserId *string `json:"parentRecipientUserId,omitempty"`
	CustomerProfile *WhatsappGroupCustomerProfile `json:"customerProfile,omitempty"`
	// Errors returned by WhatsApp for this participant.
	Errors []map[string]interface{} `json:"errors,omitempty"`
}

// NewWhatsappGroupWebhookParticipant instantiates a new WhatsappGroupWebhookParticipant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappGroupWebhookParticipant() *WhatsappGroupWebhookParticipant {
	this := WhatsappGroupWebhookParticipant{}
	return &this
}

// NewWhatsappGroupWebhookParticipantWithDefaults instantiates a new WhatsappGroupWebhookParticipant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappGroupWebhookParticipantWithDefaults() *WhatsappGroupWebhookParticipant {
	this := WhatsappGroupWebhookParticipant{}
	return &this
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookParticipant) GetInput() string {
	if o == nil || o.Input == nil {
		var ret string
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookParticipant) GetInputOk() (*string, bool) {
	if o == nil || o.Input == nil {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookParticipant) HasInput() bool {
	if o != nil && o.Input != nil {
		return true
	}

	return false
}

// SetInput gets a reference to the given string and assigns it to the Input field.
func (o *WhatsappGroupWebhookParticipant) SetInput(v string) {
	o.Input = &v
}

// GetWaId returns the WaId field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookParticipant) GetWaId() string {
	if o == nil || o.WaId == nil {
		var ret string
		return ret
	}
	return *o.WaId
}

// GetWaIdOk returns a tuple with the WaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookParticipant) GetWaIdOk() (*string, bool) {
	if o == nil || o.WaId == nil {
		return nil, false
	}
	return o.WaId, true
}

// HasWaId returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookParticipant) HasWaId() bool {
	if o != nil && o.WaId != nil {
		return true
	}

	return false
}

// SetWaId gets a reference to the given string and assigns it to the WaId field.
func (o *WhatsappGroupWebhookParticipant) SetWaId(v string) {
	o.WaId = &v
}

// GetRecipientUserId returns the RecipientUserId field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookParticipant) GetRecipientUserId() string {
	if o == nil || o.RecipientUserId == nil {
		var ret string
		return ret
	}
	return *o.RecipientUserId
}

// GetRecipientUserIdOk returns a tuple with the RecipientUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookParticipant) GetRecipientUserIdOk() (*string, bool) {
	if o == nil || o.RecipientUserId == nil {
		return nil, false
	}
	return o.RecipientUserId, true
}

// HasRecipientUserId returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookParticipant) HasRecipientUserId() bool {
	if o != nil && o.RecipientUserId != nil {
		return true
	}

	return false
}

// SetRecipientUserId gets a reference to the given string and assigns it to the RecipientUserId field.
func (o *WhatsappGroupWebhookParticipant) SetRecipientUserId(v string) {
	o.RecipientUserId = &v
}

// GetParentRecipientUserId returns the ParentRecipientUserId field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookParticipant) GetParentRecipientUserId() string {
	if o == nil || o.ParentRecipientUserId == nil {
		var ret string
		return ret
	}
	return *o.ParentRecipientUserId
}

// GetParentRecipientUserIdOk returns a tuple with the ParentRecipientUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookParticipant) GetParentRecipientUserIdOk() (*string, bool) {
	if o == nil || o.ParentRecipientUserId == nil {
		return nil, false
	}
	return o.ParentRecipientUserId, true
}

// HasParentRecipientUserId returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookParticipant) HasParentRecipientUserId() bool {
	if o != nil && o.ParentRecipientUserId != nil {
		return true
	}

	return false
}

// SetParentRecipientUserId gets a reference to the given string and assigns it to the ParentRecipientUserId field.
func (o *WhatsappGroupWebhookParticipant) SetParentRecipientUserId(v string) {
	o.ParentRecipientUserId = &v
}

// GetCustomerProfile returns the CustomerProfile field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookParticipant) GetCustomerProfile() WhatsappGroupCustomerProfile {
	if o == nil || o.CustomerProfile == nil {
		var ret WhatsappGroupCustomerProfile
		return ret
	}
	return *o.CustomerProfile
}

// GetCustomerProfileOk returns a tuple with the CustomerProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookParticipant) GetCustomerProfileOk() (*WhatsappGroupCustomerProfile, bool) {
	if o == nil || o.CustomerProfile == nil {
		return nil, false
	}
	return o.CustomerProfile, true
}

// HasCustomerProfile returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookParticipant) HasCustomerProfile() bool {
	if o != nil && o.CustomerProfile != nil {
		return true
	}

	return false
}

// SetCustomerProfile gets a reference to the given WhatsappGroupCustomerProfile and assigns it to the CustomerProfile field.
func (o *WhatsappGroupWebhookParticipant) SetCustomerProfile(v WhatsappGroupCustomerProfile) {
	o.CustomerProfile = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookParticipant) GetErrors() []map[string]interface{} {
	if o == nil || o.Errors == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookParticipant) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookParticipant) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *WhatsappGroupWebhookParticipant) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

func (o WhatsappGroupWebhookParticipant) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Input != nil {
		toSerialize["input"] = o.Input
	}
	if o.WaId != nil {
		toSerialize["waId"] = o.WaId
	}
	if o.RecipientUserId != nil {
		toSerialize["recipientUserId"] = o.RecipientUserId
	}
	if o.ParentRecipientUserId != nil {
		toSerialize["parentRecipientUserId"] = o.ParentRecipientUserId
	}
	if o.CustomerProfile != nil {
		toSerialize["customerProfile"] = o.CustomerProfile
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappGroupWebhookParticipant struct {
	value *WhatsappGroupWebhookParticipant
	isSet bool
}

func (v NullableWhatsappGroupWebhookParticipant) Get() *WhatsappGroupWebhookParticipant {
	return v.value
}

func (v *NullableWhatsappGroupWebhookParticipant) Set(val *WhatsappGroupWebhookParticipant) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappGroupWebhookParticipant) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappGroupWebhookParticipant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappGroupWebhookParticipant(val *WhatsappGroupWebhookParticipant) *NullableWhatsappGroupWebhookParticipant {
	return &NullableWhatsappGroupWebhookParticipant{value: val, isSet: true}
}

func (v NullableWhatsappGroupWebhookParticipant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappGroupWebhookParticipant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


