/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappFlowList200Response struct for WhatsappFlowList200Response
type WhatsappFlowList200Response struct {
	// List of flows.
	Items []WhatsappFlow `json:"items,omitempty"`
}

// NewWhatsappFlowList200Response instantiates a new WhatsappFlowList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappFlowList200Response() *WhatsappFlowList200Response {
	this := WhatsappFlowList200Response{}
	return &this
}

// NewWhatsappFlowList200ResponseWithDefaults instantiates a new WhatsappFlowList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappFlowList200ResponseWithDefaults() *WhatsappFlowList200Response {
	this := WhatsappFlowList200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *WhatsappFlowList200Response) GetItems() []WhatsappFlow {
	if o == nil || o.Items == nil {
		var ret []WhatsappFlow
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappFlowList200Response) GetItemsOk() ([]WhatsappFlow, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *WhatsappFlowList200Response) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WhatsappFlow and assigns it to the Items field.
func (o *WhatsappFlowList200Response) SetItems(v []WhatsappFlow) {
	o.Items = v
}

func (o WhatsappFlowList200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappFlowList200Response struct {
	value *WhatsappFlowList200Response
	isSet bool
}

func (v NullableWhatsappFlowList200Response) Get() *WhatsappFlowList200Response {
	return v.value
}

func (v *NullableWhatsappFlowList200Response) Set(val *WhatsappFlowList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappFlowList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappFlowList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappFlowList200Response(val *WhatsappFlowList200Response) *NullableWhatsappFlowList200Response {
	return &NullableWhatsappFlowList200Response{value: val, isSet: true}
}

func (v NullableWhatsappFlowList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappFlowList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


