/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
	"time"
)

// WhatsappBusinessUsername Business Username state for a WhatsApp business phone number.
type WhatsappBusinessUsername struct {
	// Phone number ID.
	Id *string `json:"id,omitempty"`
	// WhatsApp Business Account ID.
	WabaId *string `json:"wabaId,omitempty"`
	// Phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// Display phone number.
	DisplayPhoneNumber *string `json:"displayPhoneNumber,omitempty"`
	// Active Business Username. The value is a plain username without `@`.
	BusinessUsername *string `json:"businessUsername,omitempty"`
	BusinessUsernameStatus *WhatsappBusinessUsernameStatus `json:"businessUsernameStatus,omitempty"`
	// Last requested Business Username that is still under review. This value can coexist with an active `businessUsername` while the new request is pending.
	RequestedBusinessUsername *string `json:"requestedBusinessUsername,omitempty"`
	// The time when the Business Username state was last updated.
	BusinessUsernameUpdatedAt *time.Time `json:"businessUsernameUpdatedAt,omitempty"`
}

// NewWhatsappBusinessUsername instantiates a new WhatsappBusinessUsername object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappBusinessUsername() *WhatsappBusinessUsername {
	this := WhatsappBusinessUsername{}
	return &this
}

// NewWhatsappBusinessUsernameWithDefaults instantiates a new WhatsappBusinessUsername object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappBusinessUsernameWithDefaults() *WhatsappBusinessUsername {
	this := WhatsappBusinessUsername{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WhatsappBusinessUsername) SetId(v string) {
	o.Id = &v
}

// GetWabaId returns the WabaId field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetWabaId() string {
	if o == nil || o.WabaId == nil {
		var ret string
		return ret
	}
	return *o.WabaId
}

// GetWabaIdOk returns a tuple with the WabaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetWabaIdOk() (*string, bool) {
	if o == nil || o.WabaId == nil {
		return nil, false
	}
	return o.WabaId, true
}

// HasWabaId returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasWabaId() bool {
	if o != nil && o.WabaId != nil {
		return true
	}

	return false
}

// SetWabaId gets a reference to the given string and assigns it to the WabaId field.
func (o *WhatsappBusinessUsername) SetWabaId(v string) {
	o.WabaId = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *WhatsappBusinessUsername) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetDisplayPhoneNumber returns the DisplayPhoneNumber field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetDisplayPhoneNumber() string {
	if o == nil || o.DisplayPhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.DisplayPhoneNumber
}

// GetDisplayPhoneNumberOk returns a tuple with the DisplayPhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetDisplayPhoneNumberOk() (*string, bool) {
	if o == nil || o.DisplayPhoneNumber == nil {
		return nil, false
	}
	return o.DisplayPhoneNumber, true
}

// HasDisplayPhoneNumber returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasDisplayPhoneNumber() bool {
	if o != nil && o.DisplayPhoneNumber != nil {
		return true
	}

	return false
}

// SetDisplayPhoneNumber gets a reference to the given string and assigns it to the DisplayPhoneNumber field.
func (o *WhatsappBusinessUsername) SetDisplayPhoneNumber(v string) {
	o.DisplayPhoneNumber = &v
}

// GetBusinessUsername returns the BusinessUsername field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetBusinessUsername() string {
	if o == nil || o.BusinessUsername == nil {
		var ret string
		return ret
	}
	return *o.BusinessUsername
}

// GetBusinessUsernameOk returns a tuple with the BusinessUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetBusinessUsernameOk() (*string, bool) {
	if o == nil || o.BusinessUsername == nil {
		return nil, false
	}
	return o.BusinessUsername, true
}

// HasBusinessUsername returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasBusinessUsername() bool {
	if o != nil && o.BusinessUsername != nil {
		return true
	}

	return false
}

// SetBusinessUsername gets a reference to the given string and assigns it to the BusinessUsername field.
func (o *WhatsappBusinessUsername) SetBusinessUsername(v string) {
	o.BusinessUsername = &v
}

// GetBusinessUsernameStatus returns the BusinessUsernameStatus field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetBusinessUsernameStatus() WhatsappBusinessUsernameStatus {
	if o == nil || o.BusinessUsernameStatus == nil {
		var ret WhatsappBusinessUsernameStatus
		return ret
	}
	return *o.BusinessUsernameStatus
}

// GetBusinessUsernameStatusOk returns a tuple with the BusinessUsernameStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetBusinessUsernameStatusOk() (*WhatsappBusinessUsernameStatus, bool) {
	if o == nil || o.BusinessUsernameStatus == nil {
		return nil, false
	}
	return o.BusinessUsernameStatus, true
}

// HasBusinessUsernameStatus returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasBusinessUsernameStatus() bool {
	if o != nil && o.BusinessUsernameStatus != nil {
		return true
	}

	return false
}

// SetBusinessUsernameStatus gets a reference to the given WhatsappBusinessUsernameStatus and assigns it to the BusinessUsernameStatus field.
func (o *WhatsappBusinessUsername) SetBusinessUsernameStatus(v WhatsappBusinessUsernameStatus) {
	o.BusinessUsernameStatus = &v
}

// GetRequestedBusinessUsername returns the RequestedBusinessUsername field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetRequestedBusinessUsername() string {
	if o == nil || o.RequestedBusinessUsername == nil {
		var ret string
		return ret
	}
	return *o.RequestedBusinessUsername
}

// GetRequestedBusinessUsernameOk returns a tuple with the RequestedBusinessUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetRequestedBusinessUsernameOk() (*string, bool) {
	if o == nil || o.RequestedBusinessUsername == nil {
		return nil, false
	}
	return o.RequestedBusinessUsername, true
}

// HasRequestedBusinessUsername returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasRequestedBusinessUsername() bool {
	if o != nil && o.RequestedBusinessUsername != nil {
		return true
	}

	return false
}

// SetRequestedBusinessUsername gets a reference to the given string and assigns it to the RequestedBusinessUsername field.
func (o *WhatsappBusinessUsername) SetRequestedBusinessUsername(v string) {
	o.RequestedBusinessUsername = &v
}

// GetBusinessUsernameUpdatedAt returns the BusinessUsernameUpdatedAt field value if set, zero value otherwise.
func (o *WhatsappBusinessUsername) GetBusinessUsernameUpdatedAt() time.Time {
	if o == nil || o.BusinessUsernameUpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.BusinessUsernameUpdatedAt
}

// GetBusinessUsernameUpdatedAtOk returns a tuple with the BusinessUsernameUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappBusinessUsername) GetBusinessUsernameUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.BusinessUsernameUpdatedAt == nil {
		return nil, false
	}
	return o.BusinessUsernameUpdatedAt, true
}

// HasBusinessUsernameUpdatedAt returns a boolean if a field has been set.
func (o *WhatsappBusinessUsername) HasBusinessUsernameUpdatedAt() bool {
	if o != nil && o.BusinessUsernameUpdatedAt != nil {
		return true
	}

	return false
}

// SetBusinessUsernameUpdatedAt gets a reference to the given time.Time and assigns it to the BusinessUsernameUpdatedAt field.
func (o *WhatsappBusinessUsername) SetBusinessUsernameUpdatedAt(v time.Time) {
	o.BusinessUsernameUpdatedAt = &v
}

func (o WhatsappBusinessUsername) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.WabaId != nil {
		toSerialize["wabaId"] = o.WabaId
	}
	if o.PhoneNumber != nil {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if o.DisplayPhoneNumber != nil {
		toSerialize["displayPhoneNumber"] = o.DisplayPhoneNumber
	}
	if o.BusinessUsername != nil {
		toSerialize["businessUsername"] = o.BusinessUsername
	}
	if o.BusinessUsernameStatus != nil {
		toSerialize["businessUsernameStatus"] = o.BusinessUsernameStatus
	}
	if o.RequestedBusinessUsername != nil {
		toSerialize["requestedBusinessUsername"] = o.RequestedBusinessUsername
	}
	if o.BusinessUsernameUpdatedAt != nil {
		toSerialize["businessUsernameUpdatedAt"] = o.BusinessUsernameUpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappBusinessUsername struct {
	value *WhatsappBusinessUsername
	isSet bool
}

func (v NullableWhatsappBusinessUsername) Get() *WhatsappBusinessUsername {
	return v.value
}

func (v *NullableWhatsappBusinessUsername) Set(val *WhatsappBusinessUsername) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappBusinessUsername) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappBusinessUsername) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappBusinessUsername(val *WhatsappBusinessUsername) *NullableWhatsappBusinessUsername {
	return &NullableWhatsappBusinessUsername{value: val, isSet: true}
}

func (v NullableWhatsappBusinessUsername) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappBusinessUsername) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


