/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappTemplateComponentLimitedTimeOffer Use for `LIMITED_TIME_OFFER` components.
type WhatsappTemplateComponentLimitedTimeOffer struct {
	// **Required.** Offer details text. Maximum 16 characters.
	Text *string `json:"text,omitempty"`
	// **Optional.** Set to `true` to have the [offer expiration details](https://developers.facebook.com/docs/whatsapp/business-management-api/message-templates/limited-time-offer-templates#offer-expiration-details) appear in the delivered message. If set to `true`, the copy code button component must be included in the `buttons` array, and must appear first in the array. If set to `false`, offer expiration details will not appear in the delivered message and the copy code button component is optional. If including the copy code button, it must appear first in the `buttons` array.
	HasExpiration *bool `json:"has_expiration,omitempty"`
}

// NewWhatsappTemplateComponentLimitedTimeOffer instantiates a new WhatsappTemplateComponentLimitedTimeOffer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappTemplateComponentLimitedTimeOffer() *WhatsappTemplateComponentLimitedTimeOffer {
	this := WhatsappTemplateComponentLimitedTimeOffer{}
	return &this
}

// NewWhatsappTemplateComponentLimitedTimeOfferWithDefaults instantiates a new WhatsappTemplateComponentLimitedTimeOffer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappTemplateComponentLimitedTimeOfferWithDefaults() *WhatsappTemplateComponentLimitedTimeOffer {
	this := WhatsappTemplateComponentLimitedTimeOffer{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *WhatsappTemplateComponentLimitedTimeOffer) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappTemplateComponentLimitedTimeOffer) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *WhatsappTemplateComponentLimitedTimeOffer) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *WhatsappTemplateComponentLimitedTimeOffer) SetText(v string) {
	o.Text = &v
}

// GetHasExpiration returns the HasExpiration field value if set, zero value otherwise.
func (o *WhatsappTemplateComponentLimitedTimeOffer) GetHasExpiration() bool {
	if o == nil || o.HasExpiration == nil {
		var ret bool
		return ret
	}
	return *o.HasExpiration
}

// GetHasExpirationOk returns a tuple with the HasExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappTemplateComponentLimitedTimeOffer) GetHasExpirationOk() (*bool, bool) {
	if o == nil || o.HasExpiration == nil {
		return nil, false
	}
	return o.HasExpiration, true
}

// HasHasExpiration returns a boolean if a field has been set.
func (o *WhatsappTemplateComponentLimitedTimeOffer) HasHasExpiration() bool {
	if o != nil && o.HasExpiration != nil {
		return true
	}

	return false
}

// SetHasExpiration gets a reference to the given bool and assigns it to the HasExpiration field.
func (o *WhatsappTemplateComponentLimitedTimeOffer) SetHasExpiration(v bool) {
	o.HasExpiration = &v
}

func (o WhatsappTemplateComponentLimitedTimeOffer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	if o.HasExpiration != nil {
		toSerialize["has_expiration"] = o.HasExpiration
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappTemplateComponentLimitedTimeOffer struct {
	value *WhatsappTemplateComponentLimitedTimeOffer
	isSet bool
}

func (v NullableWhatsappTemplateComponentLimitedTimeOffer) Get() *WhatsappTemplateComponentLimitedTimeOffer {
	return v.value
}

func (v *NullableWhatsappTemplateComponentLimitedTimeOffer) Set(val *WhatsappTemplateComponentLimitedTimeOffer) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappTemplateComponentLimitedTimeOffer) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappTemplateComponentLimitedTimeOffer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappTemplateComponentLimitedTimeOffer(val *WhatsappTemplateComponentLimitedTimeOffer) *NullableWhatsappTemplateComponentLimitedTimeOffer {
	return &NullableWhatsappTemplateComponentLimitedTimeOffer{value: val, isSet: true}
}

func (v NullableWhatsappTemplateComponentLimitedTimeOffer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappTemplateComponentLimitedTimeOffer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
