/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappInboundMessageOrder When a customer places an order, the message type is set to `order`, and this field is included.
type WhatsappInboundMessageOrder struct {
	// The catalog ID.
	CatalogId *string `json:"catalog_id,omitempty"`
	ProductItems []WhatsappInboundMessageOrderProductItem `json:"product_items,omitempty"`
	// Text message sent along with the order.
	Text *string `json:"text,omitempty"`
}

// NewWhatsappInboundMessageOrder instantiates a new WhatsappInboundMessageOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappInboundMessageOrder() *WhatsappInboundMessageOrder {
	this := WhatsappInboundMessageOrder{}
	return &this
}

// NewWhatsappInboundMessageOrderWithDefaults instantiates a new WhatsappInboundMessageOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappInboundMessageOrderWithDefaults() *WhatsappInboundMessageOrder {
	this := WhatsappInboundMessageOrder{}
	return &this
}

// GetCatalogId returns the CatalogId field value if set, zero value otherwise.
func (o *WhatsappInboundMessageOrder) GetCatalogId() string {
	if o == nil || o.CatalogId == nil {
		var ret string
		return ret
	}
	return *o.CatalogId
}

// GetCatalogIdOk returns a tuple with the CatalogId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappInboundMessageOrder) GetCatalogIdOk() (*string, bool) {
	if o == nil || o.CatalogId == nil {
		return nil, false
	}
	return o.CatalogId, true
}

// HasCatalogId returns a boolean if a field has been set.
func (o *WhatsappInboundMessageOrder) HasCatalogId() bool {
	if o != nil && o.CatalogId != nil {
		return true
	}

	return false
}

// SetCatalogId gets a reference to the given string and assigns it to the CatalogId field.
func (o *WhatsappInboundMessageOrder) SetCatalogId(v string) {
	o.CatalogId = &v
}

// GetProductItems returns the ProductItems field value if set, zero value otherwise.
func (o *WhatsappInboundMessageOrder) GetProductItems() []WhatsappInboundMessageOrderProductItem {
	if o == nil || o.ProductItems == nil {
		var ret []WhatsappInboundMessageOrderProductItem
		return ret
	}
	return o.ProductItems
}

// GetProductItemsOk returns a tuple with the ProductItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappInboundMessageOrder) GetProductItemsOk() ([]WhatsappInboundMessageOrderProductItem, bool) {
	if o == nil || o.ProductItems == nil {
		return nil, false
	}
	return o.ProductItems, true
}

// HasProductItems returns a boolean if a field has been set.
func (o *WhatsappInboundMessageOrder) HasProductItems() bool {
	if o != nil && o.ProductItems != nil {
		return true
	}

	return false
}

// SetProductItems gets a reference to the given []WhatsappInboundMessageOrderProductItem and assigns it to the ProductItems field.
func (o *WhatsappInboundMessageOrder) SetProductItems(v []WhatsappInboundMessageOrderProductItem) {
	o.ProductItems = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *WhatsappInboundMessageOrder) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappInboundMessageOrder) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *WhatsappInboundMessageOrder) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *WhatsappInboundMessageOrder) SetText(v string) {
	o.Text = &v
}

func (o WhatsappInboundMessageOrder) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CatalogId != nil {
		toSerialize["catalog_id"] = o.CatalogId
	}
	if o.ProductItems != nil {
		toSerialize["product_items"] = o.ProductItems
	}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappInboundMessageOrder struct {
	value *WhatsappInboundMessageOrder
	isSet bool
}

func (v NullableWhatsappInboundMessageOrder) Get() *WhatsappInboundMessageOrder {
	return v.value
}

func (v *NullableWhatsappInboundMessageOrder) Set(val *WhatsappInboundMessageOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappInboundMessageOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappInboundMessageOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappInboundMessageOrder(val *WhatsappInboundMessageOrder) *NullableWhatsappInboundMessageOrder {
	return &NullableWhatsappInboundMessageOrder{value: val, isSet: true}
}

func (v NullableWhatsappInboundMessageOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappInboundMessageOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


