/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappGroupWebhookPricing Pricing information included in group message status webhooks.
type WhatsappGroupWebhookPricing struct {
	// Whether the message is billable.
	Billable *bool `json:"billable,omitempty"`
	// Pricing model.
	PricingModel *string `json:"pricingModel,omitempty"`
	// Pricing type.
	Type *string `json:"type,omitempty"`
	// Pricing category.
	Category *string `json:"category,omitempty"`
}

// NewWhatsappGroupWebhookPricing instantiates a new WhatsappGroupWebhookPricing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappGroupWebhookPricing() *WhatsappGroupWebhookPricing {
	this := WhatsappGroupWebhookPricing{}
	return &this
}

// NewWhatsappGroupWebhookPricingWithDefaults instantiates a new WhatsappGroupWebhookPricing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappGroupWebhookPricingWithDefaults() *WhatsappGroupWebhookPricing {
	this := WhatsappGroupWebhookPricing{}
	return &this
}

// GetBillable returns the Billable field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookPricing) GetBillable() bool {
	if o == nil || o.Billable == nil {
		var ret bool
		return ret
	}
	return *o.Billable
}

// GetBillableOk returns a tuple with the Billable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookPricing) GetBillableOk() (*bool, bool) {
	if o == nil || o.Billable == nil {
		return nil, false
	}
	return o.Billable, true
}

// HasBillable returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookPricing) HasBillable() bool {
	if o != nil && o.Billable != nil {
		return true
	}

	return false
}

// SetBillable gets a reference to the given bool and assigns it to the Billable field.
func (o *WhatsappGroupWebhookPricing) SetBillable(v bool) {
	o.Billable = &v
}

// GetPricingModel returns the PricingModel field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookPricing) GetPricingModel() string {
	if o == nil || o.PricingModel == nil {
		var ret string
		return ret
	}
	return *o.PricingModel
}

// GetPricingModelOk returns a tuple with the PricingModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookPricing) GetPricingModelOk() (*string, bool) {
	if o == nil || o.PricingModel == nil {
		return nil, false
	}
	return o.PricingModel, true
}

// HasPricingModel returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookPricing) HasPricingModel() bool {
	if o != nil && o.PricingModel != nil {
		return true
	}

	return false
}

// SetPricingModel gets a reference to the given string and assigns it to the PricingModel field.
func (o *WhatsappGroupWebhookPricing) SetPricingModel(v string) {
	o.PricingModel = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookPricing) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookPricing) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookPricing) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WhatsappGroupWebhookPricing) SetType(v string) {
	o.Type = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookPricing) GetCategory() string {
	if o == nil || o.Category == nil {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookPricing) GetCategoryOk() (*string, bool) {
	if o == nil || o.Category == nil {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookPricing) HasCategory() bool {
	if o != nil && o.Category != nil {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *WhatsappGroupWebhookPricing) SetCategory(v string) {
	o.Category = &v
}

func (o WhatsappGroupWebhookPricing) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Billable != nil {
		toSerialize["billable"] = o.Billable
	}
	if o.PricingModel != nil {
		toSerialize["pricingModel"] = o.PricingModel
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappGroupWebhookPricing struct {
	value *WhatsappGroupWebhookPricing
	isSet bool
}

func (v NullableWhatsappGroupWebhookPricing) Get() *WhatsappGroupWebhookPricing {
	return v.value
}

func (v *NullableWhatsappGroupWebhookPricing) Set(val *WhatsappGroupWebhookPricing) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappGroupWebhookPricing) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappGroupWebhookPricing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappGroupWebhookPricing(val *WhatsappGroupWebhookPricing) *NullableWhatsappGroupWebhookPricing {
	return &NullableWhatsappGroupWebhookPricing{value: val, isSet: true}
}

func (v NullableWhatsappGroupWebhookPricing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappGroupWebhookPricing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


