/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappPhoneNumberSettingsCalling Calling feature settings for the phone number.
type WhatsappPhoneNumberSettingsCalling struct {
	// Phone number ID.
	Id *string `json:"id,omitempty"`
	// Calling feature status: - `ENABLED`: Calling feature is enabled - `DISABLED`: Calling feature is disabled
	Status *string `json:"status,omitempty"`
	// Calling icon display configuration: - `DEFAULT`: Show icon by default - `DISABLE_ALL`: Hide all calling icons
	IconVisibility *string `json:"iconVisibility,omitempty"`
}

// NewWhatsappPhoneNumberSettingsCalling instantiates a new WhatsappPhoneNumberSettingsCalling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappPhoneNumberSettingsCalling() *WhatsappPhoneNumberSettingsCalling {
	this := WhatsappPhoneNumberSettingsCalling{}
	return &this
}

// NewWhatsappPhoneNumberSettingsCallingWithDefaults instantiates a new WhatsappPhoneNumberSettingsCalling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappPhoneNumberSettingsCallingWithDefaults() *WhatsappPhoneNumberSettingsCalling {
	this := WhatsappPhoneNumberSettingsCalling{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WhatsappPhoneNumberSettingsCalling) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappPhoneNumberSettingsCalling) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WhatsappPhoneNumberSettingsCalling) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WhatsappPhoneNumberSettingsCalling) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WhatsappPhoneNumberSettingsCalling) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappPhoneNumberSettingsCalling) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WhatsappPhoneNumberSettingsCalling) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WhatsappPhoneNumberSettingsCalling) SetStatus(v string) {
	o.Status = &v
}

// GetIconVisibility returns the IconVisibility field value if set, zero value otherwise.
func (o *WhatsappPhoneNumberSettingsCalling) GetIconVisibility() string {
	if o == nil || o.IconVisibility == nil {
		var ret string
		return ret
	}
	return *o.IconVisibility
}

// GetIconVisibilityOk returns a tuple with the IconVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappPhoneNumberSettingsCalling) GetIconVisibilityOk() (*string, bool) {
	if o == nil || o.IconVisibility == nil {
		return nil, false
	}
	return o.IconVisibility, true
}

// HasIconVisibility returns a boolean if a field has been set.
func (o *WhatsappPhoneNumberSettingsCalling) HasIconVisibility() bool {
	if o != nil && o.IconVisibility != nil {
		return true
	}

	return false
}

// SetIconVisibility gets a reference to the given string and assigns it to the IconVisibility field.
func (o *WhatsappPhoneNumberSettingsCalling) SetIconVisibility(v string) {
	o.IconVisibility = &v
}

func (o WhatsappPhoneNumberSettingsCalling) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.IconVisibility != nil {
		toSerialize["iconVisibility"] = o.IconVisibility
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappPhoneNumberSettingsCalling struct {
	value *WhatsappPhoneNumberSettingsCalling
	isSet bool
}

func (v NullableWhatsappPhoneNumberSettingsCalling) Get() *WhatsappPhoneNumberSettingsCalling {
	return v.value
}

func (v *NullableWhatsappPhoneNumberSettingsCalling) Set(val *WhatsappPhoneNumberSettingsCalling) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappPhoneNumberSettingsCalling) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappPhoneNumberSettingsCalling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappPhoneNumberSettingsCalling(val *WhatsappPhoneNumberSettingsCalling) *NullableWhatsappPhoneNumberSettingsCalling {
	return &NullableWhatsappPhoneNumberSettingsCalling{value: val, isSet: true}
}

func (v NullableWhatsappPhoneNumberSettingsCalling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappPhoneNumberSettingsCalling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


