/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappMessageOrderDetails Contains the order details when sending a template message with a `order_details` button.
type WhatsappMessageOrderDetails struct {
	// The currency for this order. Currently the only supported value is `INR`.
	Currency string `json:"currency"`
	Order WhatsappMessageOrderInfo `json:"order"`
	// Unique identifier for the order provided by the business. It is case sensitive and cannot be an empty string and can only contain English letters, numbers, underscores, dashes, or dots, and should not exceed 35 characters.  The `reference_id` must be unique for each order_details message for a given business. If there is a need to send multiple order_details messages for the same order, it is recommended to include a sequence number in the reference_id (for example, \"BM345A-12\") to ensure reference_id uniqueness.
	ReferenceId string `json:"reference_id"`
	TotalAmount WhatsappMessageOrderAmount `json:"total_amount"`
	// The type of goods being paid for in this order. Current supported options are `digital-goods` and `physical-goods`.
	Type string `json:"type"`
	// Payment settings for the order.
	PaymentSettings []WhatsappMessageOrderPaymentSetting `json:"payment_settings"`
}

// NewWhatsappMessageOrderDetails instantiates a new WhatsappMessageOrderDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappMessageOrderDetails(currency string, order WhatsappMessageOrderInfo, referenceId string, totalAmount WhatsappMessageOrderAmount, type_ string, paymentSettings []WhatsappMessageOrderPaymentSetting) *WhatsappMessageOrderDetails {
	this := WhatsappMessageOrderDetails{}
	this.Currency = currency
	this.Order = order
	this.ReferenceId = referenceId
	this.TotalAmount = totalAmount
	this.Type = type_
	this.PaymentSettings = paymentSettings
	return &this
}

// NewWhatsappMessageOrderDetailsWithDefaults instantiates a new WhatsappMessageOrderDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappMessageOrderDetailsWithDefaults() *WhatsappMessageOrderDetails {
	this := WhatsappMessageOrderDetails{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *WhatsappMessageOrderDetails) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *WhatsappMessageOrderDetails) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *WhatsappMessageOrderDetails) SetCurrency(v string) {
	o.Currency = v
}

// GetOrder returns the Order field value
func (o *WhatsappMessageOrderDetails) GetOrder() WhatsappMessageOrderInfo {
	if o == nil {
		var ret WhatsappMessageOrderInfo
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *WhatsappMessageOrderDetails) GetOrderOk() (*WhatsappMessageOrderInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *WhatsappMessageOrderDetails) SetOrder(v WhatsappMessageOrderInfo) {
	o.Order = v
}

// GetReferenceId returns the ReferenceId field value
func (o *WhatsappMessageOrderDetails) GetReferenceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *WhatsappMessageOrderDetails) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *WhatsappMessageOrderDetails) SetReferenceId(v string) {
	o.ReferenceId = v
}

// GetTotalAmount returns the TotalAmount field value
func (o *WhatsappMessageOrderDetails) GetTotalAmount() WhatsappMessageOrderAmount {
	if o == nil {
		var ret WhatsappMessageOrderAmount
		return ret
	}

	return o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value
// and a boolean to check if the value has been set.
func (o *WhatsappMessageOrderDetails) GetTotalAmountOk() (*WhatsappMessageOrderAmount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAmount, true
}

// SetTotalAmount sets field value
func (o *WhatsappMessageOrderDetails) SetTotalAmount(v WhatsappMessageOrderAmount) {
	o.TotalAmount = v
}

// GetType returns the Type field value
func (o *WhatsappMessageOrderDetails) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WhatsappMessageOrderDetails) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WhatsappMessageOrderDetails) SetType(v string) {
	o.Type = v
}

// GetPaymentSettings returns the PaymentSettings field value
func (o *WhatsappMessageOrderDetails) GetPaymentSettings() []WhatsappMessageOrderPaymentSetting {
	if o == nil {
		var ret []WhatsappMessageOrderPaymentSetting
		return ret
	}

	return o.PaymentSettings
}

// GetPaymentSettingsOk returns a tuple with the PaymentSettings field value
// and a boolean to check if the value has been set.
func (o *WhatsappMessageOrderDetails) GetPaymentSettingsOk() ([]WhatsappMessageOrderPaymentSetting, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentSettings, true
}

// SetPaymentSettings sets field value
func (o *WhatsappMessageOrderDetails) SetPaymentSettings(v []WhatsappMessageOrderPaymentSetting) {
	o.PaymentSettings = v
}

func (o WhatsappMessageOrderDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if true {
		toSerialize["order"] = o.Order
	}
	if true {
		toSerialize["reference_id"] = o.ReferenceId
	}
	if true {
		toSerialize["total_amount"] = o.TotalAmount
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["payment_settings"] = o.PaymentSettings
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappMessageOrderDetails struct {
	value *WhatsappMessageOrderDetails
	isSet bool
}

func (v NullableWhatsappMessageOrderDetails) Get() *WhatsappMessageOrderDetails {
	return v.value
}

func (v *NullableWhatsappMessageOrderDetails) Set(val *WhatsappMessageOrderDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappMessageOrderDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappMessageOrderDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappMessageOrderDetails(val *WhatsappMessageOrderDetails) *NullableWhatsappMessageOrderDetails {
	return &NullableWhatsappMessageOrderDetails{value: val, isSet: true}
}

func (v NullableWhatsappMessageOrderDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappMessageOrderDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


