/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappFlowCreateRequest struct for WhatsappFlowCreateRequest
type WhatsappFlowCreateRequest struct {
	// WhatsApp Business Account ID.
	WabaId string `json:"wabaId"`
	// Flow name.
	Name string `json:"name"`
	// Flow categories.
	Categories []WhatsappFlowCategory `json:"categories"`
	// JSON string of the Flow structure.
	FlowJson *string `json:"flowJson,omitempty"`
	// If true, the Flow will be created in PUBLISHED state.
	Publish *bool `json:"publish,omitempty"`
	// ID of source Flow to clone. You must have permission to access the specified Flow.
	CloneFlowId *string `json:"cloneFlowId,omitempty"`
}

// NewWhatsappFlowCreateRequest instantiates a new WhatsappFlowCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappFlowCreateRequest(wabaId string, name string, categories []WhatsappFlowCategory) *WhatsappFlowCreateRequest {
	this := WhatsappFlowCreateRequest{}
	this.WabaId = wabaId
	this.Name = name
	this.Categories = categories
	var publish bool = false
	this.Publish = &publish
	return &this
}

// NewWhatsappFlowCreateRequestWithDefaults instantiates a new WhatsappFlowCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappFlowCreateRequestWithDefaults() *WhatsappFlowCreateRequest {
	this := WhatsappFlowCreateRequest{}
	var publish bool = false
	this.Publish = &publish
	return &this
}

// GetWabaId returns the WabaId field value
func (o *WhatsappFlowCreateRequest) GetWabaId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WabaId
}

// GetWabaIdOk returns a tuple with the WabaId field value
// and a boolean to check if the value has been set.
func (o *WhatsappFlowCreateRequest) GetWabaIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WabaId, true
}

// SetWabaId sets field value
func (o *WhatsappFlowCreateRequest) SetWabaId(v string) {
	o.WabaId = v
}

// GetName returns the Name field value
func (o *WhatsappFlowCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WhatsappFlowCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WhatsappFlowCreateRequest) SetName(v string) {
	o.Name = v
}

// GetCategories returns the Categories field value
func (o *WhatsappFlowCreateRequest) GetCategories() []WhatsappFlowCategory {
	if o == nil {
		var ret []WhatsappFlowCategory
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *WhatsappFlowCreateRequest) GetCategoriesOk() ([]WhatsappFlowCategory, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *WhatsappFlowCreateRequest) SetCategories(v []WhatsappFlowCategory) {
	o.Categories = v
}

// GetFlowJson returns the FlowJson field value if set, zero value otherwise.
func (o *WhatsappFlowCreateRequest) GetFlowJson() string {
	if o == nil || o.FlowJson == nil {
		var ret string
		return ret
	}
	return *o.FlowJson
}

// GetFlowJsonOk returns a tuple with the FlowJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappFlowCreateRequest) GetFlowJsonOk() (*string, bool) {
	if o == nil || o.FlowJson == nil {
		return nil, false
	}
	return o.FlowJson, true
}

// HasFlowJson returns a boolean if a field has been set.
func (o *WhatsappFlowCreateRequest) HasFlowJson() bool {
	if o != nil && o.FlowJson != nil {
		return true
	}

	return false
}

// SetFlowJson gets a reference to the given string and assigns it to the FlowJson field.
func (o *WhatsappFlowCreateRequest) SetFlowJson(v string) {
	o.FlowJson = &v
}

// GetPublish returns the Publish field value if set, zero value otherwise.
func (o *WhatsappFlowCreateRequest) GetPublish() bool {
	if o == nil || o.Publish == nil {
		var ret bool
		return ret
	}
	return *o.Publish
}

// GetPublishOk returns a tuple with the Publish field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappFlowCreateRequest) GetPublishOk() (*bool, bool) {
	if o == nil || o.Publish == nil {
		return nil, false
	}
	return o.Publish, true
}

// HasPublish returns a boolean if a field has been set.
func (o *WhatsappFlowCreateRequest) HasPublish() bool {
	if o != nil && o.Publish != nil {
		return true
	}

	return false
}

// SetPublish gets a reference to the given bool and assigns it to the Publish field.
func (o *WhatsappFlowCreateRequest) SetPublish(v bool) {
	o.Publish = &v
}

// GetCloneFlowId returns the CloneFlowId field value if set, zero value otherwise.
func (o *WhatsappFlowCreateRequest) GetCloneFlowId() string {
	if o == nil || o.CloneFlowId == nil {
		var ret string
		return ret
	}
	return *o.CloneFlowId
}

// GetCloneFlowIdOk returns a tuple with the CloneFlowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappFlowCreateRequest) GetCloneFlowIdOk() (*string, bool) {
	if o == nil || o.CloneFlowId == nil {
		return nil, false
	}
	return o.CloneFlowId, true
}

// HasCloneFlowId returns a boolean if a field has been set.
func (o *WhatsappFlowCreateRequest) HasCloneFlowId() bool {
	if o != nil && o.CloneFlowId != nil {
		return true
	}

	return false
}

// SetCloneFlowId gets a reference to the given string and assigns it to the CloneFlowId field.
func (o *WhatsappFlowCreateRequest) SetCloneFlowId(v string) {
	o.CloneFlowId = &v
}

func (o WhatsappFlowCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["wabaId"] = o.WabaId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["categories"] = o.Categories
	}
	if o.FlowJson != nil {
		toSerialize["flowJson"] = o.FlowJson
	}
	if o.Publish != nil {
		toSerialize["publish"] = o.Publish
	}
	if o.CloneFlowId != nil {
		toSerialize["cloneFlowId"] = o.CloneFlowId
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappFlowCreateRequest struct {
	value *WhatsappFlowCreateRequest
	isSet bool
}

func (v NullableWhatsappFlowCreateRequest) Get() *WhatsappFlowCreateRequest {
	return v.value
}

func (v *NullableWhatsappFlowCreateRequest) Set(val *WhatsappFlowCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappFlowCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappFlowCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappFlowCreateRequest(val *WhatsappFlowCreateRequest) *NullableWhatsappFlowCreateRequest {
	return &NullableWhatsappFlowCreateRequest{value: val, isSet: true}
}

func (v NullableWhatsappFlowCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappFlowCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


