/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WebhookEndpointCreateRequest struct for WebhookEndpointCreateRequest
type WebhookEndpointCreateRequest struct {
	// The URL of the webhook endpoint.
	Url string `json:"url"`
	// The list of events to enable for this endpoint.
	EnabledEvents []EventType `json:"enabledEvents"`
	// Optional configuration for event properties in webhook payloads. Specifies which properties should be included for specific event types. When `enabledEvents` contains `contact.attributes_changed`, this field is required and must contain at least one event property configuration for that event type.
	EventProperties []EventProperty `json:"eventProperties,omitempty"`
	// An optional description of what the webhook is used for.
	Description *string `json:"description,omitempty"`
	Status *WebhookEndpointStatus `json:"status,omitempty"`
}

// NewWebhookEndpointCreateRequest instantiates a new WebhookEndpointCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointCreateRequest(url string, enabledEvents []EventType) *WebhookEndpointCreateRequest {
	this := WebhookEndpointCreateRequest{}
	this.Url = url
	this.EnabledEvents = enabledEvents
	return &this
}

// NewWebhookEndpointCreateRequestWithDefaults instantiates a new WebhookEndpointCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointCreateRequestWithDefaults() *WebhookEndpointCreateRequest {
	this := WebhookEndpointCreateRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookEndpointCreateRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpointCreateRequest) SetUrl(v string) {
	o.Url = v
}

// GetEnabledEvents returns the EnabledEvents field value
func (o *WebhookEndpointCreateRequest) GetEnabledEvents() []EventType {
	if o == nil {
		var ret []EventType
		return ret
	}

	return o.EnabledEvents
}

// GetEnabledEventsOk returns a tuple with the EnabledEvents field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetEnabledEventsOk() ([]EventType, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledEvents, true
}

// SetEnabledEvents sets field value
func (o *WebhookEndpointCreateRequest) SetEnabledEvents(v []EventType) {
	o.EnabledEvents = v
}

// GetEventProperties returns the EventProperties field value if set, zero value otherwise.
func (o *WebhookEndpointCreateRequest) GetEventProperties() []EventProperty {
	if o == nil || o.EventProperties == nil {
		var ret []EventProperty
		return ret
	}
	return o.EventProperties
}

// GetEventPropertiesOk returns a tuple with the EventProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetEventPropertiesOk() ([]EventProperty, bool) {
	if o == nil || o.EventProperties == nil {
		return nil, false
	}
	return o.EventProperties, true
}

// HasEventProperties returns a boolean if a field has been set.
func (o *WebhookEndpointCreateRequest) HasEventProperties() bool {
	if o != nil && o.EventProperties != nil {
		return true
	}

	return false
}

// SetEventProperties gets a reference to the given []EventProperty and assigns it to the EventProperties field.
func (o *WebhookEndpointCreateRequest) SetEventProperties(v []EventProperty) {
	o.EventProperties = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WebhookEndpointCreateRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookEndpointCreateRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WebhookEndpointCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WebhookEndpointCreateRequest) GetStatus() WebhookEndpointStatus {
	if o == nil || o.Status == nil {
		var ret WebhookEndpointStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreateRequest) GetStatusOk() (*WebhookEndpointStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WebhookEndpointCreateRequest) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given WebhookEndpointStatus and assigns it to the Status field.
func (o *WebhookEndpointCreateRequest) SetStatus(v WebhookEndpointStatus) {
	o.Status = &v
}

func (o WebhookEndpointCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["enabledEvents"] = o.EnabledEvents
	}
	if o.EventProperties != nil {
		toSerialize["eventProperties"] = o.EventProperties
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableWebhookEndpointCreateRequest struct {
	value *WebhookEndpointCreateRequest
	isSet bool
}

func (v NullableWebhookEndpointCreateRequest) Get() *WebhookEndpointCreateRequest {
	return v.value
}

func (v *NullableWebhookEndpointCreateRequest) Set(val *WebhookEndpointCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointCreateRequest(val *WebhookEndpointCreateRequest) *NullableWebhookEndpointCreateRequest {
	return &NullableWebhookEndpointCreateRequest{value: val, isSet: true}
}

func (v NullableWebhookEndpointCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


