/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappGroupJoinRequestActionResponse Result of approving or rejecting group join requests.
type WhatsappGroupJoinRequestActionResponse struct {
	// Approved join request IDs.
	ApprovedJoinRequests []string `json:"approvedJoinRequests,omitempty"`
	// Rejected join request IDs.
	RejectedJoinRequests []string `json:"rejectedJoinRequests,omitempty"`
	// Join requests that failed to be processed.
	FailedJoinRequests []WhatsappGroupFailedJoinRequest `json:"failedJoinRequests,omitempty"`
	// Errors returned by WhatsApp.
	Errors []map[string]interface{} `json:"errors,omitempty"`
}

// NewWhatsappGroupJoinRequestActionResponse instantiates a new WhatsappGroupJoinRequestActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappGroupJoinRequestActionResponse() *WhatsappGroupJoinRequestActionResponse {
	this := WhatsappGroupJoinRequestActionResponse{}
	return &this
}

// NewWhatsappGroupJoinRequestActionResponseWithDefaults instantiates a new WhatsappGroupJoinRequestActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappGroupJoinRequestActionResponseWithDefaults() *WhatsappGroupJoinRequestActionResponse {
	this := WhatsappGroupJoinRequestActionResponse{}
	return &this
}

// GetApprovedJoinRequests returns the ApprovedJoinRequests field value if set, zero value otherwise.
func (o *WhatsappGroupJoinRequestActionResponse) GetApprovedJoinRequests() []string {
	if o == nil || o.ApprovedJoinRequests == nil {
		var ret []string
		return ret
	}
	return o.ApprovedJoinRequests
}

// GetApprovedJoinRequestsOk returns a tuple with the ApprovedJoinRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupJoinRequestActionResponse) GetApprovedJoinRequestsOk() ([]string, bool) {
	if o == nil || o.ApprovedJoinRequests == nil {
		return nil, false
	}
	return o.ApprovedJoinRequests, true
}

// HasApprovedJoinRequests returns a boolean if a field has been set.
func (o *WhatsappGroupJoinRequestActionResponse) HasApprovedJoinRequests() bool {
	if o != nil && o.ApprovedJoinRequests != nil {
		return true
	}

	return false
}

// SetApprovedJoinRequests gets a reference to the given []string and assigns it to the ApprovedJoinRequests field.
func (o *WhatsappGroupJoinRequestActionResponse) SetApprovedJoinRequests(v []string) {
	o.ApprovedJoinRequests = v
}

// GetRejectedJoinRequests returns the RejectedJoinRequests field value if set, zero value otherwise.
func (o *WhatsappGroupJoinRequestActionResponse) GetRejectedJoinRequests() []string {
	if o == nil || o.RejectedJoinRequests == nil {
		var ret []string
		return ret
	}
	return o.RejectedJoinRequests
}

// GetRejectedJoinRequestsOk returns a tuple with the RejectedJoinRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupJoinRequestActionResponse) GetRejectedJoinRequestsOk() ([]string, bool) {
	if o == nil || o.RejectedJoinRequests == nil {
		return nil, false
	}
	return o.RejectedJoinRequests, true
}

// HasRejectedJoinRequests returns a boolean if a field has been set.
func (o *WhatsappGroupJoinRequestActionResponse) HasRejectedJoinRequests() bool {
	if o != nil && o.RejectedJoinRequests != nil {
		return true
	}

	return false
}

// SetRejectedJoinRequests gets a reference to the given []string and assigns it to the RejectedJoinRequests field.
func (o *WhatsappGroupJoinRequestActionResponse) SetRejectedJoinRequests(v []string) {
	o.RejectedJoinRequests = v
}

// GetFailedJoinRequests returns the FailedJoinRequests field value if set, zero value otherwise.
func (o *WhatsappGroupJoinRequestActionResponse) GetFailedJoinRequests() []WhatsappGroupFailedJoinRequest {
	if o == nil || o.FailedJoinRequests == nil {
		var ret []WhatsappGroupFailedJoinRequest
		return ret
	}
	return o.FailedJoinRequests
}

// GetFailedJoinRequestsOk returns a tuple with the FailedJoinRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupJoinRequestActionResponse) GetFailedJoinRequestsOk() ([]WhatsappGroupFailedJoinRequest, bool) {
	if o == nil || o.FailedJoinRequests == nil {
		return nil, false
	}
	return o.FailedJoinRequests, true
}

// HasFailedJoinRequests returns a boolean if a field has been set.
func (o *WhatsappGroupJoinRequestActionResponse) HasFailedJoinRequests() bool {
	if o != nil && o.FailedJoinRequests != nil {
		return true
	}

	return false
}

// SetFailedJoinRequests gets a reference to the given []WhatsappGroupFailedJoinRequest and assigns it to the FailedJoinRequests field.
func (o *WhatsappGroupJoinRequestActionResponse) SetFailedJoinRequests(v []WhatsappGroupFailedJoinRequest) {
	o.FailedJoinRequests = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *WhatsappGroupJoinRequestActionResponse) GetErrors() []map[string]interface{} {
	if o == nil || o.Errors == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupJoinRequestActionResponse) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *WhatsappGroupJoinRequestActionResponse) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *WhatsappGroupJoinRequestActionResponse) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

func (o WhatsappGroupJoinRequestActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApprovedJoinRequests != nil {
		toSerialize["approvedJoinRequests"] = o.ApprovedJoinRequests
	}
	if o.RejectedJoinRequests != nil {
		toSerialize["rejectedJoinRequests"] = o.RejectedJoinRequests
	}
	if o.FailedJoinRequests != nil {
		toSerialize["failedJoinRequests"] = o.FailedJoinRequests
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappGroupJoinRequestActionResponse struct {
	value *WhatsappGroupJoinRequestActionResponse
	isSet bool
}

func (v NullableWhatsappGroupJoinRequestActionResponse) Get() *WhatsappGroupJoinRequestActionResponse {
	return v.value
}

func (v *NullableWhatsappGroupJoinRequestActionResponse) Set(val *WhatsappGroupJoinRequestActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappGroupJoinRequestActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappGroupJoinRequestActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappGroupJoinRequestActionResponse(val *WhatsappGroupJoinRequestActionResponse) *NullableWhatsappGroupJoinRequestActionResponse {
	return &NullableWhatsappGroupJoinRequestActionResponse{value: val, isSet: true}
}

func (v NullableWhatsappGroupJoinRequestActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappGroupJoinRequestActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


