/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappCallingConnectRequest struct for WhatsappCallingConnectRequest
type WhatsappCallingConnectRequest struct {
	// The caller's phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
	From string `json:"from"`
	// The callee's phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.
	To string `json:"to"`
	// The SDP type, must be \"offer\" for connection requests.
	SdpType string `json:"sdpType"`
	// The Session Description Protocol (SDP) offer information compliant with [RFC 8866](https://datatracker.ietf.org/doc/html/rfc8866). Contains media session parameters for establishing the WebRTC connection.
	Sdp string `json:"sdp"`
}

// NewWhatsappCallingConnectRequest instantiates a new WhatsappCallingConnectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappCallingConnectRequest(from string, to string, sdpType string, sdp string) *WhatsappCallingConnectRequest {
	this := WhatsappCallingConnectRequest{}
	this.From = from
	this.To = to
	this.SdpType = sdpType
	this.Sdp = sdp
	return &this
}

// NewWhatsappCallingConnectRequestWithDefaults instantiates a new WhatsappCallingConnectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappCallingConnectRequestWithDefaults() *WhatsappCallingConnectRequest {
	this := WhatsappCallingConnectRequest{}
	return &this
}

// GetFrom returns the From field value
func (o *WhatsappCallingConnectRequest) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *WhatsappCallingConnectRequest) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *WhatsappCallingConnectRequest) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *WhatsappCallingConnectRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *WhatsappCallingConnectRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *WhatsappCallingConnectRequest) SetTo(v string) {
	o.To = v
}

// GetSdpType returns the SdpType field value
func (o *WhatsappCallingConnectRequest) GetSdpType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SdpType
}

// GetSdpTypeOk returns a tuple with the SdpType field value
// and a boolean to check if the value has been set.
func (o *WhatsappCallingConnectRequest) GetSdpTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SdpType, true
}

// SetSdpType sets field value
func (o *WhatsappCallingConnectRequest) SetSdpType(v string) {
	o.SdpType = v
}

// GetSdp returns the Sdp field value
func (o *WhatsappCallingConnectRequest) GetSdp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sdp
}

// GetSdpOk returns a tuple with the Sdp field value
// and a boolean to check if the value has been set.
func (o *WhatsappCallingConnectRequest) GetSdpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sdp, true
}

// SetSdp sets field value
func (o *WhatsappCallingConnectRequest) SetSdp(v string) {
	o.Sdp = v
}

func (o WhatsappCallingConnectRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["sdpType"] = o.SdpType
	}
	if true {
		toSerialize["sdp"] = o.Sdp
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappCallingConnectRequest struct {
	value *WhatsappCallingConnectRequest
	isSet bool
}

func (v NullableWhatsappCallingConnectRequest) Get() *WhatsappCallingConnectRequest {
	return v.value
}

func (v *NullableWhatsappCallingConnectRequest) Set(val *WhatsappCallingConnectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappCallingConnectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappCallingConnectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappCallingConnectRequest(val *WhatsappCallingConnectRequest) *NullableWhatsappCallingConnectRequest {
	return &NullableWhatsappCallingConnectRequest{value: val, isSet: true}
}

func (v NullableWhatsappCallingConnectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappCallingConnectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


