/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappFlowUpdateMetadataRequest struct for WhatsappFlowUpdateMetadataRequest
type WhatsappFlowUpdateMetadataRequest struct {
	// Flow name.
	Name *string `json:"name,omitempty"`
	// Flow categories.
	Categories []WhatsappFlowCategory `json:"categories,omitempty"`
}

// NewWhatsappFlowUpdateMetadataRequest instantiates a new WhatsappFlowUpdateMetadataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappFlowUpdateMetadataRequest() *WhatsappFlowUpdateMetadataRequest {
	this := WhatsappFlowUpdateMetadataRequest{}
	return &this
}

// NewWhatsappFlowUpdateMetadataRequestWithDefaults instantiates a new WhatsappFlowUpdateMetadataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappFlowUpdateMetadataRequestWithDefaults() *WhatsappFlowUpdateMetadataRequest {
	this := WhatsappFlowUpdateMetadataRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WhatsappFlowUpdateMetadataRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappFlowUpdateMetadataRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WhatsappFlowUpdateMetadataRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WhatsappFlowUpdateMetadataRequest) SetName(v string) {
	o.Name = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *WhatsappFlowUpdateMetadataRequest) GetCategories() []WhatsappFlowCategory {
	if o == nil || o.Categories == nil {
		var ret []WhatsappFlowCategory
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappFlowUpdateMetadataRequest) GetCategoriesOk() ([]WhatsappFlowCategory, bool) {
	if o == nil || o.Categories == nil {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *WhatsappFlowUpdateMetadataRequest) HasCategories() bool {
	if o != nil && o.Categories != nil {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []WhatsappFlowCategory and assigns it to the Categories field.
func (o *WhatsappFlowUpdateMetadataRequest) SetCategories(v []WhatsappFlowCategory) {
	o.Categories = v
}

func (o WhatsappFlowUpdateMetadataRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Categories != nil {
		toSerialize["categories"] = o.Categories
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappFlowUpdateMetadataRequest struct {
	value *WhatsappFlowUpdateMetadataRequest
	isSet bool
}

func (v NullableWhatsappFlowUpdateMetadataRequest) Get() *WhatsappFlowUpdateMetadataRequest {
	return v.value
}

func (v *NullableWhatsappFlowUpdateMetadataRequest) Set(val *WhatsappFlowUpdateMetadataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappFlowUpdateMetadataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappFlowUpdateMetadataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappFlowUpdateMetadataRequest(val *WhatsappFlowUpdateMetadataRequest) *NullableWhatsappFlowUpdateMetadataRequest {
	return &NullableWhatsappFlowUpdateMetadataRequest{value: val, isSet: true}
}

func (v NullableWhatsappFlowUpdateMetadataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappFlowUpdateMetadataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


