/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappMessageInteractiveActionCard A card object in `interactive` messages. All cards must have the same structure.
type WhatsappMessageInteractiveActionCard struct {
	// Card index. Unique index for each card (0-9).
	CardIndex *float32 `json:"card_index,omitempty"`
	// Must be \"cta_url\".
	Type *string `json:"type,omitempty"`
	Header *WhatsappMessageInteractiveActionCardHeader `json:"header,omitempty"`
	Body *WhatsappMessageInteractiveActionCardBody `json:"body,omitempty"`
	Action *WhatsappMessageInteractiveActionCardAction `json:"action,omitempty"`
}

// NewWhatsappMessageInteractiveActionCard instantiates a new WhatsappMessageInteractiveActionCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappMessageInteractiveActionCard() *WhatsappMessageInteractiveActionCard {
	this := WhatsappMessageInteractiveActionCard{}
	return &this
}

// NewWhatsappMessageInteractiveActionCardWithDefaults instantiates a new WhatsappMessageInteractiveActionCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappMessageInteractiveActionCardWithDefaults() *WhatsappMessageInteractiveActionCard {
	this := WhatsappMessageInteractiveActionCard{}
	return &this
}

// GetCardIndex returns the CardIndex field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionCard) GetCardIndex() float32 {
	if o == nil || o.CardIndex == nil {
		var ret float32
		return ret
	}
	return *o.CardIndex
}

// GetCardIndexOk returns a tuple with the CardIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionCard) GetCardIndexOk() (*float32, bool) {
	if o == nil || o.CardIndex == nil {
		return nil, false
	}
	return o.CardIndex, true
}

// HasCardIndex returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionCard) HasCardIndex() bool {
	if o != nil && o.CardIndex != nil {
		return true
	}

	return false
}

// SetCardIndex gets a reference to the given float32 and assigns it to the CardIndex field.
func (o *WhatsappMessageInteractiveActionCard) SetCardIndex(v float32) {
	o.CardIndex = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionCard) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionCard) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionCard) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WhatsappMessageInteractiveActionCard) SetType(v string) {
	o.Type = &v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionCard) GetHeader() WhatsappMessageInteractiveActionCardHeader {
	if o == nil || o.Header == nil {
		var ret WhatsappMessageInteractiveActionCardHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionCard) GetHeaderOk() (*WhatsappMessageInteractiveActionCardHeader, bool) {
	if o == nil || o.Header == nil {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionCard) HasHeader() bool {
	if o != nil && o.Header != nil {
		return true
	}

	return false
}

// SetHeader gets a reference to the given WhatsappMessageInteractiveActionCardHeader and assigns it to the Header field.
func (o *WhatsappMessageInteractiveActionCard) SetHeader(v WhatsappMessageInteractiveActionCardHeader) {
	o.Header = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionCard) GetBody() WhatsappMessageInteractiveActionCardBody {
	if o == nil || o.Body == nil {
		var ret WhatsappMessageInteractiveActionCardBody
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionCard) GetBodyOk() (*WhatsappMessageInteractiveActionCardBody, bool) {
	if o == nil || o.Body == nil {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionCard) HasBody() bool {
	if o != nil && o.Body != nil {
		return true
	}

	return false
}

// SetBody gets a reference to the given WhatsappMessageInteractiveActionCardBody and assigns it to the Body field.
func (o *WhatsappMessageInteractiveActionCard) SetBody(v WhatsappMessageInteractiveActionCardBody) {
	o.Body = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionCard) GetAction() WhatsappMessageInteractiveActionCardAction {
	if o == nil || o.Action == nil {
		var ret WhatsappMessageInteractiveActionCardAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionCard) GetActionOk() (*WhatsappMessageInteractiveActionCardAction, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionCard) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given WhatsappMessageInteractiveActionCardAction and assigns it to the Action field.
func (o *WhatsappMessageInteractiveActionCard) SetAction(v WhatsappMessageInteractiveActionCardAction) {
	o.Action = &v
}

func (o WhatsappMessageInteractiveActionCard) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CardIndex != nil {
		toSerialize["card_index"] = o.CardIndex
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Header != nil {
		toSerialize["header"] = o.Header
	}
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappMessageInteractiveActionCard struct {
	value *WhatsappMessageInteractiveActionCard
	isSet bool
}

func (v NullableWhatsappMessageInteractiveActionCard) Get() *WhatsappMessageInteractiveActionCard {
	return v.value
}

func (v *NullableWhatsappMessageInteractiveActionCard) Set(val *WhatsappMessageInteractiveActionCard) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappMessageInteractiveActionCard) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappMessageInteractiveActionCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappMessageInteractiveActionCard(val *WhatsappMessageInteractiveActionCard) *NullableWhatsappMessageInteractiveActionCard {
	return &NullableWhatsappMessageInteractiveActionCard{value: val, isSet: true}
}

func (v NullableWhatsappMessageInteractiveActionCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappMessageInteractiveActionCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


