/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappMessageInteractiveActionSectionsInner [WhatsApp Section Object](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#section-object).
type WhatsappMessageInteractiveActionSectionsInner struct {
	// Title of the section.
	Title *string `json:"title,omitempty"`
	// Contains a list of rows. You can have a total of 10 rows across your sections. Each row must have a title (Maximum length: 24 characters) and an ID (Maximum length: 200 characters). You can add a description (Maximum length: 72 characters), but it is optional.
	Rows []WhatsappMessageInteractiveActionSectionsInnerRowsInner `json:"rows,omitempty"`
}

// NewWhatsappMessageInteractiveActionSectionsInner instantiates a new WhatsappMessageInteractiveActionSectionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappMessageInteractiveActionSectionsInner() *WhatsappMessageInteractiveActionSectionsInner {
	this := WhatsappMessageInteractiveActionSectionsInner{}
	return &this
}

// NewWhatsappMessageInteractiveActionSectionsInnerWithDefaults instantiates a new WhatsappMessageInteractiveActionSectionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappMessageInteractiveActionSectionsInnerWithDefaults() *WhatsappMessageInteractiveActionSectionsInner {
	this := WhatsappMessageInteractiveActionSectionsInner{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionSectionsInner) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionSectionsInner) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionSectionsInner) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *WhatsappMessageInteractiveActionSectionsInner) SetTitle(v string) {
	o.Title = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *WhatsappMessageInteractiveActionSectionsInner) GetRows() []WhatsappMessageInteractiveActionSectionsInnerRowsInner {
	if o == nil || o.Rows == nil {
		var ret []WhatsappMessageInteractiveActionSectionsInnerRowsInner
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappMessageInteractiveActionSectionsInner) GetRowsOk() ([]WhatsappMessageInteractiveActionSectionsInnerRowsInner, bool) {
	if o == nil || o.Rows == nil {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *WhatsappMessageInteractiveActionSectionsInner) HasRows() bool {
	if o != nil && o.Rows != nil {
		return true
	}

	return false
}

// SetRows gets a reference to the given []WhatsappMessageInteractiveActionSectionsInnerRowsInner and assigns it to the Rows field.
func (o *WhatsappMessageInteractiveActionSectionsInner) SetRows(v []WhatsappMessageInteractiveActionSectionsInnerRowsInner) {
	o.Rows = v
}

func (o WhatsappMessageInteractiveActionSectionsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Rows != nil {
		toSerialize["rows"] = o.Rows
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappMessageInteractiveActionSectionsInner struct {
	value *WhatsappMessageInteractiveActionSectionsInner
	isSet bool
}

func (v NullableWhatsappMessageInteractiveActionSectionsInner) Get() *WhatsappMessageInteractiveActionSectionsInner {
	return v.value
}

func (v *NullableWhatsappMessageInteractiveActionSectionsInner) Set(val *WhatsappMessageInteractiveActionSectionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappMessageInteractiveActionSectionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappMessageInteractiveActionSectionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappMessageInteractiveActionSectionsInner(val *WhatsappMessageInteractiveActionSectionsInner) *NullableWhatsappMessageInteractiveActionSectionsInner {
	return &NullableWhatsappMessageInteractiveActionSectionsInner{value: val, isSet: true}
}

func (v NullableWhatsappMessageInteractiveActionSectionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappMessageInteractiveActionSectionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


