/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappGroupWebhookConversationOrigin struct for WhatsappGroupWebhookConversationOrigin
type WhatsappGroupWebhookConversationOrigin struct {
	// Conversation origin type.
	Type *string `json:"type,omitempty"`
}

// NewWhatsappGroupWebhookConversationOrigin instantiates a new WhatsappGroupWebhookConversationOrigin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappGroupWebhookConversationOrigin() *WhatsappGroupWebhookConversationOrigin {
	this := WhatsappGroupWebhookConversationOrigin{}
	return &this
}

// NewWhatsappGroupWebhookConversationOriginWithDefaults instantiates a new WhatsappGroupWebhookConversationOrigin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappGroupWebhookConversationOriginWithDefaults() *WhatsappGroupWebhookConversationOrigin {
	this := WhatsappGroupWebhookConversationOrigin{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WhatsappGroupWebhookConversationOrigin) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupWebhookConversationOrigin) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WhatsappGroupWebhookConversationOrigin) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WhatsappGroupWebhookConversationOrigin) SetType(v string) {
	o.Type = &v
}

func (o WhatsappGroupWebhookConversationOrigin) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappGroupWebhookConversationOrigin struct {
	value *WhatsappGroupWebhookConversationOrigin
	isSet bool
}

func (v NullableWhatsappGroupWebhookConversationOrigin) Get() *WhatsappGroupWebhookConversationOrigin {
	return v.value
}

func (v *NullableWhatsappGroupWebhookConversationOrigin) Set(val *WhatsappGroupWebhookConversationOrigin) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappGroupWebhookConversationOrigin) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappGroupWebhookConversationOrigin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappGroupWebhookConversationOrigin(val *WhatsappGroupWebhookConversationOrigin) *NullableWhatsappGroupWebhookConversationOrigin {
	return &NullableWhatsappGroupWebhookConversationOrigin{value: val, isSet: true}
}

func (v NullableWhatsappGroupWebhookConversationOrigin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappGroupWebhookConversationOrigin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


