/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappGroupListItem WhatsApp group list item.
type WhatsappGroupListItem struct {
	// WhatsApp group ID.
	GroupId *string `json:"groupId,omitempty"`
	// The group subject.
	Subject *string `json:"subject,omitempty"`
	// Unix timestamp indicating when the group was created.
	CreatedAt *int64 `json:"createdAt,omitempty"`
}

// NewWhatsappGroupListItem instantiates a new WhatsappGroupListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappGroupListItem() *WhatsappGroupListItem {
	this := WhatsappGroupListItem{}
	return &this
}

// NewWhatsappGroupListItemWithDefaults instantiates a new WhatsappGroupListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappGroupListItemWithDefaults() *WhatsappGroupListItem {
	this := WhatsappGroupListItem{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *WhatsappGroupListItem) GetGroupId() string {
	if o == nil || o.GroupId == nil {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupListItem) GetGroupIdOk() (*string, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *WhatsappGroupListItem) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *WhatsappGroupListItem) SetGroupId(v string) {
	o.GroupId = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *WhatsappGroupListItem) GetSubject() string {
	if o == nil || o.Subject == nil {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupListItem) GetSubjectOk() (*string, bool) {
	if o == nil || o.Subject == nil {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *WhatsappGroupListItem) HasSubject() bool {
	if o != nil && o.Subject != nil {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *WhatsappGroupListItem) SetSubject(v string) {
	o.Subject = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WhatsappGroupListItem) GetCreatedAt() int64 {
	if o == nil || o.CreatedAt == nil {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappGroupListItem) GetCreatedAtOk() (*int64, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WhatsappGroupListItem) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *WhatsappGroupListItem) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

func (o WhatsappGroupListItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupId != nil {
		toSerialize["groupId"] = o.GroupId
	}
	if o.Subject != nil {
		toSerialize["subject"] = o.Subject
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappGroupListItem struct {
	value *WhatsappGroupListItem
	isSet bool
}

func (v NullableWhatsappGroupListItem) Get() *WhatsappGroupListItem {
	return v.value
}

func (v *NullableWhatsappGroupListItem) Set(val *WhatsappGroupListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappGroupListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappGroupListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappGroupListItem(val *WhatsappGroupListItem) *NullableWhatsappGroupListItem {
	return &NullableWhatsappGroupListItem{value: val, isSet: true}
}

func (v NullableWhatsappGroupListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappGroupListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


