/*
YCloud API

The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.

API version: v2
Contact: service@ycloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ycloud

import (
	"encoding/json"
)

// WhatsappInboundMessageReferredProduct A Product Inquiry Message is received when a user is asking for more information about a specific product. These can be received as in two scenarios: 1. When a customer replies to Single or Multi-Product Messages. 2. When a customer accesses a business’ catalog through another entry point, navigates to a Product Details Page, and clicks Message Business about this Product.
type WhatsappInboundMessageReferredProduct struct {
	// The catalog ID.
	CatalogId *string `json:"catalog_id,omitempty"`
	// The product SKU identifier.
	ProductRetailerId *string `json:"product_retailer_id,omitempty"`
}

// NewWhatsappInboundMessageReferredProduct instantiates a new WhatsappInboundMessageReferredProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsappInboundMessageReferredProduct() *WhatsappInboundMessageReferredProduct {
	this := WhatsappInboundMessageReferredProduct{}
	return &this
}

// NewWhatsappInboundMessageReferredProductWithDefaults instantiates a new WhatsappInboundMessageReferredProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsappInboundMessageReferredProductWithDefaults() *WhatsappInboundMessageReferredProduct {
	this := WhatsappInboundMessageReferredProduct{}
	return &this
}

// GetCatalogId returns the CatalogId field value if set, zero value otherwise.
func (o *WhatsappInboundMessageReferredProduct) GetCatalogId() string {
	if o == nil || o.CatalogId == nil {
		var ret string
		return ret
	}
	return *o.CatalogId
}

// GetCatalogIdOk returns a tuple with the CatalogId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappInboundMessageReferredProduct) GetCatalogIdOk() (*string, bool) {
	if o == nil || o.CatalogId == nil {
		return nil, false
	}
	return o.CatalogId, true
}

// HasCatalogId returns a boolean if a field has been set.
func (o *WhatsappInboundMessageReferredProduct) HasCatalogId() bool {
	if o != nil && o.CatalogId != nil {
		return true
	}

	return false
}

// SetCatalogId gets a reference to the given string and assigns it to the CatalogId field.
func (o *WhatsappInboundMessageReferredProduct) SetCatalogId(v string) {
	o.CatalogId = &v
}

// GetProductRetailerId returns the ProductRetailerId field value if set, zero value otherwise.
func (o *WhatsappInboundMessageReferredProduct) GetProductRetailerId() string {
	if o == nil || o.ProductRetailerId == nil {
		var ret string
		return ret
	}
	return *o.ProductRetailerId
}

// GetProductRetailerIdOk returns a tuple with the ProductRetailerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsappInboundMessageReferredProduct) GetProductRetailerIdOk() (*string, bool) {
	if o == nil || o.ProductRetailerId == nil {
		return nil, false
	}
	return o.ProductRetailerId, true
}

// HasProductRetailerId returns a boolean if a field has been set.
func (o *WhatsappInboundMessageReferredProduct) HasProductRetailerId() bool {
	if o != nil && o.ProductRetailerId != nil {
		return true
	}

	return false
}

// SetProductRetailerId gets a reference to the given string and assigns it to the ProductRetailerId field.
func (o *WhatsappInboundMessageReferredProduct) SetProductRetailerId(v string) {
	o.ProductRetailerId = &v
}

func (o WhatsappInboundMessageReferredProduct) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CatalogId != nil {
		toSerialize["catalog_id"] = o.CatalogId
	}
	if o.ProductRetailerId != nil {
		toSerialize["product_retailer_id"] = o.ProductRetailerId
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsappInboundMessageReferredProduct struct {
	value *WhatsappInboundMessageReferredProduct
	isSet bool
}

func (v NullableWhatsappInboundMessageReferredProduct) Get() *WhatsappInboundMessageReferredProduct {
	return v.value
}

func (v *NullableWhatsappInboundMessageReferredProduct) Set(val *WhatsappInboundMessageReferredProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsappInboundMessageReferredProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsappInboundMessageReferredProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsappInboundMessageReferredProduct(val *WhatsappInboundMessageReferredProduct) *NullableWhatsappInboundMessageReferredProduct {
	return &NullableWhatsappInboundMessageReferredProduct{value: val, isSet: true}
}

func (v NullableWhatsappInboundMessageReferredProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsappInboundMessageReferredProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
